ANT:
  lora_path: 'your_lora_path'
  # >>> primary settings >>>
  multi_concept:
  - [
    ['brent-heighton', 'style'],
    ['brett-weston', 'style'],
    ['brett-whiteley', 'style'],
    ['brian-bolland', 'style'],
    ['brian-despain', 'style'],
    ['brian-froud', 'style'],
    ['brian-k.-vaughan', 'style'],
    ['brian-kesinger', 'style'],
    ['brian-mashburn', 'style'],
    ['brian-oldham', 'style'],
    ['brian-stelfreeze', 'style'],
    ['brian-sum', 'style'],
    ['briana-mora', 'style'],
    ['brice-marden', 'style'],
    ['bridget-bate-tichenor', 'style'],
    ['briton-rivière', 'style'],
    ['brooke-didonato', 'style'],
    ['brooke-shaden', 'style'],
    ['brothers-grimm', 'style'],
    ['brothers-hildebrandt', 'style'],
    ['bruce-munro', 'style'],
    ['bruce-nauman', 'style'],
    ['bruce-pennington', 'style'],
    ['bruce-timm', 'style'],
    ['bruno-catalano', 'style'],
    ['bruno-munari', 'style'],
    ['bruno-walpoth', 'style'],
    ['bryan-hitch', 'style'],
    ['butcher-billy', 'style'],
    ['c.-r.-w.-nevinson', 'style'],
    ['cagnaccio-di-san-pietro', 'style'],
    ['camille-corot', 'style'],
    ['camille-pissarro', 'style'],
    ['camille-walala', 'style'],
    ['canaletto', 'style'],
    ['candido-portinari', 'style'],
    ['carel-willink', 'style'],
    ['carl-barks', 'style'],
    ['carl-gustav-carus', 'style'],
    ['carl-holsoe', 'style'],
    ['carl-larsson', 'style'],
    ['carl-spitzweg', 'style'],
    ['carlo-crivelli', 'style'],
    ['carlos-schwabe', 'style'],
    ['carmen-saldana', 'style'],
    ['carne-griffiths', 'style'],
    ['casey-weldon', 'style'],
    ['caspar-david-friedrich', 'style'],
    ['cassius-marcellus-coolidge', 'style'],
    ['catrin-welz-stein', 'style'],
    ['cedric-peyravernay', 'style'],
    ['chad-knight', 'style'],
    ['chantal-joffe', 'style'],
    ['charles-addams', 'style'],
    ['charles-angrand', 'style'],
    ['charles-blackman', 'style'],
    ['charles-camoin', 'style'],
    ['charles-dana-gibson', 'style'],
    ['charles-e.-burchfield', 'style'],
    ['charles-gwathmey', 'style'],
    ['charles-le-brun', 'style'],
    ['charles-liu', 'style'],
    ['charles-schridde', 'style'],
    ['charles-schulz', 'style'],
    ['charles-spencelayh', 'style'],
    ['charles-vess', 'style'],
    ['charles-francois-daubigny', 'style'],
    ['charlie-bowater', 'style'],
    ['charline-von-heyl', 'style'],
    ['chaïm-soutine', 'style'],
    ['chen-zhen', 'style'],
    ['chesley-bonestell', 'style'],
    ['chiharu-shiota', 'style'],
    ['ching-yeh', 'style'],
    ['chip-zdarsky', 'style'],
    ['chris-claremont', 'style'],
    ['chris-cunningham', 'style'],
    ['chris-foss', 'style'],
    ['chris-leib', 'style'],
    ['chris-moore', 'style'],
    ['chris-ofili', 'style'],
    ['chris-saunders', 'style'],
    ['chris-turnham', 'style'],
    ['chris-uminga', 'style'],
    ['chris-van-allsburg', 'style'],
    ['chris-ware', 'style'],
    ['christian-dimitrov', 'style'],
    ['christian-grajewski', 'style'],
    ['christophe-vacher', 'style'],
    ['christopher-balaskas', 'style'],
    ['christopher-jin-baron', 'style'],
    ['chuck-close', 'style'],
    ['cicely-mary-barker', 'style'],
    ['cindy-sherman', 'style'],
    ['clara-miller-burd', 'style'],
    ['clara-peeters', 'style'],
    ['clarence-holbrook-carter', 'style'],
    ['claude-cahun', 'style'],
    ['claude-monet', 'style'],
    ['clemens-ascher', 'style'],
  ]
  use_pooler: true  
  train_batch_size: 1
  learning_rate: 1.0e-04
  max_train_steps: 50
  train_preserve_scale: 1.0e-12
  fuse_preserve_scale: 1.0e-12
  mapping_concept: 
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
    - 'art'
  augment: true
  lamb: 0.0
  rank: 1
  lora: true
  train_seperate: true
  importance_sampling: true
  max_memory: 50
  aug_length: 30
  prompt_len: 30
  resolution: 512
  all_words: false
  generate_data: true
  center_crop: false
  use_gpt: false
  test_erased_model: false
  prior_preservation_cache_path: ./cache/cache_coco.pt
  domain_preservation_cache_path: ./cache/cache_art.pt
  preserve_weight: 7e+12
  input_data_dir: ./data/100art
  
  # pretrained_model_name_or_path: stabilityai/stable-diffusion-2-1-base
  pretrained_model_name_or_path: CompVis/stable-diffusion-v1-4
  with_prior_preservation: false
  preserve_prompt: a person
  preserve_data_dir: data/a person
  prior_loss_weight: 1.0